version: "3.3"
services:
    borrowmygamedotnet:
        build:
            context: ./BorrowMyGameDotNet
            dockerfile: ../Dockerfiles/BorrowMyGameDotNet.dockerfile
        ports:
            - 5000:5000
            - 5001:5001
        depends_on: 
            - mysql
            - mongo

    nginx:
        build:
            context: .
            dockerfile: Dockerfiles/Nginx.dockerfile
        ports:
            - 8000:80
            - 6000:5000
        volumes:
            - ./Nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            #     - backend
            - frontend

    frontend:
        build:
            context: ./Frontend
            dockerfile: ../Dockerfiles/Frontend.dockerfile
        volumes:
            - ./Frontend/src:/app/src
            - ./Frontend/public:/app/public
            - ./Frontend/node_modules:/app/node_modules:rw
        tty: true
        stdin_open: true

    mysql:
        build:
            context: .
            dockerfile: Dockerfiles/Mysql.dockerfile
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - 3306:3306
        env_file:
            - .env

    mongo:
        build:
            context: .
            dockerfile: Dockerfiles/Mongo.dockerfile
        volumes:
            - mongo:/data/db
        env_file:
            - .env

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - .env
        depends_on: 
            - mongo

volumes:
    mysql:
    mongo:
